- .circleci/config.yml
- do
*Ticket/s*:   
Found a small bug from PR #27 
Change Type: 
AC:
> Fix README check

- Chart.yaml
- README.md
- changelog.md
* Bump version to 10.0.12
* Fix PDB by referencing the right variable
> chore: Add PR #31 to changelog

- Chart.yaml
- README.md
- changelog.md
- templates/deployment.yaml
- tests/deployment_test.yaml
- values.yaml
*Ticket/s*: https://circleci.atlassian.net/browse/ONPREM-966
Change Type: 
AC:
> Expose log settings in values file [ONPREM-966]

- README.md
Updating the README to match the changes made for an external contribution.
> update readme with changes for rules fix

- Chart.yaml
- README.md
*Ticket/s*:   
Change Type: Maintainance
AC:
Cut helm chart release
> Bump version for release

- Chart.yaml
- README.md
- changelog.md
- templates/deployment.yaml
- tests/deployment_test.yaml
*Ticket/s*:   
Change Type: Bug fix
AC:
Take a list of pull secrets and template them correctly
> Take list of secrets for image pull secrets

- README.md
- templates/README.md.gotmpl
README wasn't clear on support paths or contribution guidelines
*Ticket/s*:   
N/A
Update readme with some better contribution guidelines and support links.
Change Type: 
Documentation
AC:
No tests for readme update beyond git porcelain 
This PR is updating documentation
> update readme with support info

- Chart.yaml
- README.md
- changelog.md
*Ticket/s*:   ONPREM-1020
Change Type: New feature
Bump chart version & changelog to release configurable service containers
> [ONPREM-1020] Prepare 101.1.0 release

- Chart.yaml
- README.md
- changelog.md
- templates/configmap.yaml
- tests/configmap_test.yaml
*Ticket/s*:   ONPREM-1020
Change Type: bug fix
Only template the service containers if we have config & remove trailing :
Add some tests for the configmap
> [ONPREM-1020] Fix service container config template & add configmap test

- Chart.yaml
- README.md
- changelog.md
> [ONPREM-1020] Prepare release 101.1.1 (for real this time)

- changelog.md
- tests/configmap_test.yaml
- values.yaml
*Ticket/s*:   ONPREM-1025
Change Type: Bug fix
Updated the service container config to match the correct format
> [ONPREM-1025] Use correct format for service container config example

- .circleci/config.yml
*Ticket/s*:   
Change Type: 
AC:
> Run the smoke tests

- .circleci/config.yml
*Ticket/s*:  https://circleci.atlassian.net/browse/ONPREM-1189
Change Type: 
AC:
https://app.circleci.com/pipelines/github/CircleCI-Public/container-runner-helm-chart/400/workflows/7fa1a3e9-a845-4471-89ff-f1f3277e94b0/jobs/1162?invite=true#step-103-0_84
> Tag releases in GitHub [ONPREM-1189]

- Chart.yaml
- README.md
- changelog.md
- templates/role.yaml
- tests/roles_test.yaml
*Ticket/s*:   
Change Type: 
AC:
> Grant list permissions for Pods and events [ONPREM-1643]

- changelog.md
- templates/service-account.yaml
*Ticket/s*:   
I have added the namespace metadata to an object
Change Type: 
AC:
> Add namespace for service-account.yaml

- changelog.md
- templates/pdb.yaml
- values.yaml
*Ticket/s*:   
Change Type:  syntax issue
AC: 
templating issue arrises after enabling pdb in the values.yaml file . 
> indent changed to nindent

- changelog.md
- do
- templates/_helpers.tpl
- templates/logging/_helpers.tpl
- templates/logging/role.yaml
- templates/logging/secret.yaml
- templates/logging/service-account.yaml
- templates/role.yaml
- templates/service-account.yaml
- tests/kubeconform/test-ssh-values.yaml
- tests/logging/role_test.yaml
- tests/roles_test.yaml
*Ticket/s*:  https://circleci.atlassian.net/browse/ONPREM-1339
Change Type: 
AC:
> Move logging resources to their own component subdirectory [ONPREM-1339]

- README.md
- templates/clusterrole.yaml
- templates/configmap.yaml
- templates/deployment.yaml
- templates/pdb.yaml
- templates/proxy-secret.yaml
- templates/role.yaml
- templates/secrets.yaml
- templates/service-account.yaml
- templates/ssh.yaml
- tests/__snapshot__/ssh_test.yaml.snap
- values.yaml
*Ticket/s*:   ONPREM-1338
Change Type: Maintenance 
AC: Remove unneeded namespace fields from k8s resources
> [ONPREM-1338] Don't set the namespace directly where we don't need to

- README.md
- values.yaml
*Ticket/s*: https://circleci.atlassian.net/browse/ONPREM-1694
Add addition documentation to the `logging` container's Helm values, especially for its corresponding service account. 
Change Type: 
AC:
> [ONPREM-1694] Update Helm docs on logging container values

- changelog.md
- templates/deployment.yaml
*Ticket/s*:   
https://circleci.atlassian.net/browse/ONPREM-2091
Change Type: 
Adds a new environment variable so container agent can be aware of its pod name.
AC:
> [ONPREM-2091] - Add environment variable for metadata.name

- changelog.md
- templates/deployment.yaml
*Ticket/s*:   
Change Type: 
AC:
> [ONPREM-2091] - Change metadata.name environment variable to match the usage
